### ISSUE TITLE
Portal not being properly removed

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#10]
Half an api and half a portals issue it seems. Making it here anyway.

Every few, as you might know, rooms/portals might change IDs. If we're trying out to start a portal though, a big error will raise:
![](https://safe.install.sex/Jc3Ep4.png)
![](https://safe.install.sex/XUjV8n.png)

As of right now I'm not sure how to describe it - portals not being properly removed, room changing ID/not existing (even though it does, so bugged rooms?), or such. But needs proper handling.

**Comment by williamsthing** [comment]
Is `@cryb/api` running? It's trying to send a request to inform the API that the Portal is currently closed.

**Comment by JeDaYoshi** [comment]
Yes, it is... But it just raises a `ROOM_NOT_FOUND` which portals don't seem to take well.

**Comment by Soliel** [comment]
To add to this; it appears that the portal was removed from the database through a weird flow of control. This gets reproduced reliably on my site so I have tons of error logs. Bit my portals get oprhaned alot and don't end up closed.

**Comment by williamsthing** [comment]
This issue occurs when the initial Redis message from `@cryb/portals` to `@cryb/api` to inform API of the new portal id for the room. When this message isn't properly received, this error occurs when the portal is destroyed. I'll try move this message over to a HTTP request which is more versatile in terms of error handling.

**Comment by williamsthing** [comment]
This issue should be more or less fixed with the last two commits, if there are any issues then open this again 😄
