### ISSUE TITLE
Even when everything is running, and I follow noot's tutorial, I'm still getting a loop error

### ISSUE THREAD

**Issue by RW456** [crybapp/portals#13]
Title. Also, I updated it recently.

portals terminal code:
 
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound
(node:533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
socket closed localhost.localdomain portal
(node:533) UnhandledPromiseRejectionWarning: PortalNotFound

portals .env

# The environment the app is running in, either production, staging or development
NODE_ENV=development

# The base REST endpoint that is used to talk to @cryb/api
API_URL=http://server ip:4000
# This should the same secure key in @cryb/api/.env under 'PORTALS_API_KEY'
API_KEY=(my api key here)

# This should the same secure key in @cryb/portal/.env under 'PORTALS_KEY'
PORTAL_KEY=(my portal key here)

# The URI used for connecting to the MongoDB database
MONGO_URI=(same uri I use for everything else that works)
# The URI used for connecting to Redis instance
REDIS_URI=redis://localhost:6379
# If you're using redis-ha on Kubernetes, set the URI for the Sentinel below
# Make sure to uncomment the below line and uncomment the REDIS_URI line above
# REDIS_SENTINELS=

# Optional: the JSON Google Application Credentials used for gcloud.driver
# GOOGLE_APPLICATION_CREDENTIALS=

# Optional: configuration for kubernetes.driver
# The URL of the registry the image for the portal is located at
# K8S_PORTAL_IMAGE_REGISTRY_URL=
# The name of the secret for pulling the image from the registry
# K8S_PORTAL_IMAGE_PULL_SECRET=

# The name of the secret for the container env variables
# K8S_PORTAL_ENV_SECRET=

# The requested CPU limit for the portal instance
# K8S_PORTAL_CPU_LIMIT=
# The requested memory limit for the portal instance
# K8S_PORTAL_MEMORY_LIMIT=
# The requested CPU for the portal instance
# K8S_PORTAL_CPU_REQUESTED=
# The requested memory for the portal instance
# K8S_PORTAL_MEMORY_REQUESTED=

portal .env

# The environment the app is running in, either production, staging or development
NODE_ENV=development

# The base REST endpoint that is used to talk to @cryb/portals
PORTALS_WS_URL=http://my ip:1337
# This should the same secure key in @cryb/portals/.env under 'PORTAL_KEY'
PORTALS_KEY=(my portal key here)

# The URL of @cryb/aperture that ffmpeg should stream to. This should be :9000 on @cryb/aperture.
APERTURE_URL=http://my ip:9000
# This should the same secure key in @cryb/aperture/.env under 'APERTURE_WS_KEY'
APERTURE_KEY=(my aperture key)

# The Display services like Chromium and ffmpeg will use
DISPLAY=:100
# The width of the video stream in px
VIDEO_WIDTH=1280
# The height of the video stream in px
VIDEO_HEIGHT=720

**Comment by JeDaYoshi** [comment]
You seem to have not passed `--portalId` to the command - that happens in that case.

Also, ask this kind of stuff in the Cryb Discord server - closing as an invalid issue.
