### ISSUE TITLE
Google cloud not starting docker in VM

### ISSUE THREAD

**Issue by lolaustin** [crybapp/portals#14]
# Google Cloud VM

When google cloud is set up and configured, the VM isn't starting docker in google cloud compute engine.

### Output in `cryb/portals`

`using driver gcloud to open portal with id 17777798626148352
recieved message on channel portals data {"op":0,"d":{"id":"17777798626148352","roomId":"17777795182624768"},"t":"PORTAL_CREATE"}
recieved internal portal message to be routed to portal with id undefined {"op":0,"d":{"id":"17777798626148352","roomId":"17777795182624768"},"t":"PORTAL_CREATE"}
target not found for internal message to portal; aborting
opened portal with name portal-17777798626148352
`

### Output in `cryb/api`

`recieved 17777798626148352 starting from portal microservice, finding room...
room found, updating status...
status updated and online members fetched: [ '17731198600085504' ]
POST /internal/portal 200 11.428 ms - 2
[CRYB-API-DEVELOPMENT] [WS] [EMIT] Opcode: 0, type: PORTAL_UPDATE, data: {"status":"starting","lastUpdatedAt":"1571448159403","id":"17777798626148352"} to ["17731198600085504"]`

**Comment by williamsthing** [comment]
What's your instance template name?

_p.s. continuing this issue from convo on Discord_

**Comment by lolaustin** [comment]
`portal-template`

**Comment by williamsthing** [comment]
Hm, could you post a screenshot of your instance template? Make sure to blur our any sensitive info.

**Comment by lolaustin** [comment]
![Screen Shot 2019-10-18 at 9 32 47 PM](https://user-images.githubusercontent.com/28121364/67136045-f36c9200-f1ee-11e9-9c29-0be423dd0d5c.png)

**Comment by williamsthing** [comment]
Issue was that the Docker image wasn't pushed to GCR
