### ISSUE TITLE
Add an automatic Docker driver

### ISSUE THREAD

**Issue by NurMarvin** [crybapp/portals#16]
It would be great to have an automatic Docker driver that automatically starts a Docker image on the server with the appropriate portal id attached.
This is especially useful when having a bigger server or multiple smaller server and therefore don't want to pay extra for services like Google Cloud or Kubernetes.
This would need a separate service that connects to the portals web socket on port 1337 and then the portals service would look for a connected "portal manager" that is used the least.

**Comment by williamsthing** [comment]
We already have an open issue for this [here](https://github.com/crybapp/portals/issues/3), so I'm gonna close this one out for now. Thanks for the recommendation tho!
