### ISSUE TITLE
Requires Google Cloud/Kubernetes environment variables to start

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#2]
It currently won't start if those environment variables aren't defined, which is confusing as in .env they're marked as "optional", and more unhelpful, it's just errors of things directly depending of them, failing to work as they're `undefined`.

**Comment by Akrilla** [comment]
Shouldn't be marked as optional, and should gracefully handle them not being set.

**Comment by JeDaYoshi** [comment]
Exactly. And not fail if one of them is set and the other isn't.

**Comment by williamsthing** [comment]
Fixed, see https://github.com/crybapp/portals/commit/9cf20ce77e3a84dedafdeb245924b592cdbaa188.

Reopen if there's any more issues - thanks!
