### ISSUE TITLE
Create locally-hosted Docker driver.

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#3]
Surely most people interested in self-hosting Cryb, be it in a VPS, dedicated server, or even their own computer, won't like to use Google Cloud/Kubernetes on that (#2), so a driver for hosting the Docker container in the same machine `@cryb/portals` is running on would work pretty well.

**Comment by lnneth** [comment]
This should be fairly easy using the child_process library but it is not very viable at all for more than a single room

**Comment by williamsthing** [comment]
I think when I was looking at creating a Docker driver for Portals so I didn't have to do stuff manually in development I looked at this: https://www.npmjs.com/package/node-docker-api

**Comment by JeDaYoshi** [comment]
I've done this now in a70db0a. Closing! :tada:
