### ISSUE TITLE
Change REDIS_URI for REDIS_SENTINELS and add explaination

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#5]
REDIS_URI isn't used anywhere, as a normal Redis server isn't used - but sentinels. Add an explaination about this, and fix `.env.example` to have sentinels, and a little explaination there.

**Comment by JeDaYoshi** [comment]
Or, add an option to use a normal Redis server instead of sentinels, as I feel it'd be more convenient for small Cryb instances.

**Comment by williamsthing** [comment]
Fixed in https://github.com/crybapp/portals/commit/aca98a4ac51e3615043d2be21cf2b4c9f2726ff2, will add a REDIS_URI variable soon to `@cryb/api` and `@cryb/portals`.

**Comment by williamsthing** [comment]
Added the ability to use `REDIS_URI` for a normal Redis instance instead of Sentinels in https://github.com/crybapp/portals/pull/7.
