### ISSUE TITLE
Kubernetes - Working in production without running on a cluster

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#6]
By what I've seen, portals is expecting for it to be running in a Kubernetes cluster while on production. This may lead to problems as not every install would be done like this (and hasn't)

**Comment by williamsthing** [comment]
Could you link some lines or files where `@cryb/portals` is expecting to be ran on a K8S cluster? This might be linked to https://github.com/crybapp/portals/issues/2.

**Comment by JeDaYoshi** [comment]
I mention this based as the Kubernetes driver tries to load config with `LoadFromCluster()`, which tries to connect to kubernetes.io in a path on `/var/run/kubernetes.io`, as of my guess, it might be of a Kubernetes instance. I might be wrong though as of the reason.

**Comment by williamsthing** [comment]
This should be fixed in https://github.com/crybapp/portals/commit/0fbc56ab64f2268387d2fb0f4fdafcc8fa207df0, let me know if you have any issues - closing for now!
