### ISSUE TITLE
"PortalNotFound" when portal tries connecting via WebSocket

### ISSUE THREAD

**Issue by JeDaYoshi** [crybapp/portals#8]
The actual issue in crybapp/portal#3. The WebSocket between a portal and portals keeps getting closed by portals.

In `@cryb/portal`, there's an infinite log of this:
```
Attempting reconnect to @cryb/portals via WS
Connected to @cryb/portals via WS
ready? true
emitting beacon to portals server
Disconnected from @cryb/portals ws
```

While in `@cryb/portals`, we get this:
```
socket open
recieved message from undefined (unknown) over ws 2 undefined
authentication error PortalNotFound
unknown socket closed
```

Seems more of a portals issue so that's why I'm moving the issue here.

**Comment by williamsthing** [comment]
This means there isn't a entry in the DB for the portal with the id that `@cryb/portal` is being started with. If you're using the `manual` driver, `@cryb/portals` will log the command that should be run in the `@cryb/portal` dir to start everything up properly. Let me know if you run into any roadblocks!

**Comment by JeDaYoshi** [comment]
That's what everyone did, though.

People created the rooms, portals would give out the instructions to run it manually, and after we did that, we get this error.

**Comment by williamsthing** [comment]
Hm, I'll look into it further but I can't reproduce the issue locally. Can you look at your MongoDB instance using a tool like Robo 3T and show me what's inside the `portals` collection?

**Comment by MinkiNTN** [comment]
I'm having the same error. Inside my `portals` collection are 2 objects, one of which have my Portal ID
![image](https://user-images.githubusercontent.com/9282386/66942773-71dffd00-f052-11e9-9514-cc6c5aa0bf0f.png)

**Comment by JeDaYoshi** [comment]
crybapp/portal#8 might fix this.

**Comment by williamsthing** [comment]
Merged https://github.com/crybapp/portal/pull/8 into master, let me know if this helps @MinkiNTN !

**Comment by JeDaYoshi** [comment]
As far as tested, this seems to be fixed now.

**Comment by JeDaYoshi** [comment]
Forgot to close this, as it's fixed already!
